//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbound
    {
        public int Id { get; set; }
        public string InboundBrand { get; set; }
        public string InboundType { get; set; }
        public Nullable<int> InboundConteynerId { get; set; }
        public Nullable<int> SkuPiece { get; set; }
        public Nullable<int> WorkId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SkuId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Sku Sku { get; set; }
        public virtual SkuType SkuType { get; set; }
        public virtual Work Work { get; set; }
    }
}
