//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozition
    {
        public int Id { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string SkuType { get; set; }
        public Nullable<int> HallwayNumber { get; set; }
        public string ShelfLetter { get; set; }
        public Nullable<int> ShelfNumber { get; set; }
        public Nullable<int> SkuTypeId { get; set; }
    
        public virtual SkuType SkuType1 { get; set; }
    }
}
