//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozition
    {
        public int Id { get; set; }
        public string PozitionName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string SkuType { get; set; }
        public Nullable<int> SkuPiece { get; set; }
        public Nullable<int> SkuTypeId { get; set; }
        public string Availability { get; set; }
    
        public virtual SkuType SkuType1 { get; set; }
    }
}
