//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.Inbound = new HashSet<Inbound>();
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int Id { get; set; }
        public string WorkType { get; set; }
        public string WorkName { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<int> TerminalCode { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string Quadrant { get; set; }
        public Nullable<int> Sku { get; set; }
        public string Pozition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inbound> Inbound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
        public virtual Users Users { get; set; }
    }
}
